[alias]
# Format and verify aliases
fmt-all = "run --manifest-path scripts/fmt.sh"
verify = "run --manifest-path scripts/verify.sh"
pre-commit = "run --manifest-path scripts/verify.sh"
coverage = "run --manifest-path scripts/coverage.sh"

# Quick check alias
check-all = [
  "fmt -- --check",
  "clippy -- -D warnings",
  "test",
  "doc --all-features --no-deps --document-private-items",
]

# Full check with coverage
check-full = [
  "fmt -- --check",
  "clippy -- -D warnings",
  "test",
  "doc --all-features --no-deps --document-private-items",
  "run --manifest-path scripts/coverage.sh",
]
