[alias]
fmt-all = "fmt --all"
fmt-check = "fmt --all -- --check"
clippy-all = "clippy --workspace --all-targets --all-features"
clippy-fix = "clippy --workspace --all-targets --all-features --fix --allow-dirty --allow-staged"
test-all = "test --workspace --all-features"
build-all = "build --workspace --all-features --release"
doc-all = "doc --workspace --all-features --no-deps"
audit-all = "audit --deny warnings"
deny-licenses = "deny check licenses"
coverage = "tarpaulin --workspace --all-features --timeout 120 --out Html --out Json --output-dir target/coverage"

check-all = [
  "fmt --all -- --check",
  "clippy --workspace --all-targets --all-features",
  "test --workspace --all-features",
  "build --workspace --all-features --release",
]

check-full = [
  "fmt --all -- --check",
  "clippy --workspace --all-targets --all-features",
  "test --workspace --all-features",
  "doc --workspace --all-features --no-deps",
  "audit --deny warnings",
  "deny check licenses",
  "tarpaulin --workspace --all-features --timeout 120 --out Html --out Json --output-dir target/coverage",
]
